name: Build Swift App

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Compile Swift File
        run: swiftc main.swift -o LupinApp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LupinApp
          path: LupinApp
